/**
 * Writes `dist/_headers` after each build.
 *
 * Netlify and Cloudflare Pages both read that file from the publish directory.
 * It is generated rather than checked in because the Content-Security-Policy
 * pins the inline scripts by hash, and those hashes change whenever the script
 * source does. A checked-in copy would go stale silently, and a stale hash
 * blocks the script.
 *
 * Vercel ignores `_headers`; it needs the same values in `vercel.json`.
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { join } from 'node:path';

const DIST = 'dist';

const htmlFiles = (dir) =>
  readdirSync(dir).flatMap((entry) => {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) return htmlFiles(path);
    return path.endsWith('.html') ? [path] : [];
  });

/**
 * Every executable inline script on the site, hashed.
 *
 * `application/ld+json` is deliberately skipped: it is a data block, never
 * executed, and so is not subject to script-src.
 */
const scriptHashes = new Set();
for (const file of htmlFiles(DIST)) {
  const html = readFileSync(file, 'utf8');
  for (const match of html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g)) {
    const [, attrs, body] = match;
    if (attrs.includes('src=') || attrs.includes('ld+json')) continue;
    // Hashed over the exact bytes between the tags, whitespace included.
    scriptHashes.add(`'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`);
  }
}

if (scriptHashes.size === 0) {
  throw new Error('No inline scripts found. The CSP would be wrong; refusing to write _headers.');
}

const csp = [
  "default-src 'self'",
  `script-src 'self' ${[...scriptHashes].join(' ')}`,
  // The page sets custom properties through style attributes (reveal delays,
  // per-logo heights), and those need 'unsafe-inline' in style-src. It is a far
  // weaker concession than the same keyword in script-src would be.
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self'",
  // `data:` is required, not decoration. Vite inlines assets under its size
  // threshold, and one font subset falls below it, so it arrives as a data URI
  // inside the stylesheet while the other fifteen are files. `font-src 'self'`
  // alone blocks it and the page loses that face. A data: font is not a
  // meaningful attack vector: fonts do not execute, and injecting one already
  // requires the ability to inject CSS.
  "font-src 'self' data:",
  // Nothing on the page fetches anything.
  "connect-src 'none'",
  "form-action 'none'",
  "frame-ancestors 'none'",
  "base-uri 'none'",
  "object-src 'none'",
  'upgrade-insecure-requests',
].join('; ');

const headers = `# Generated by scripts/generate-headers.mjs. Do not edit by hand.
/*
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  X-Frame-Options: DENY
  Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), microphone=(), payment=(), usb=()
  Strict-Transport-Security: max-age=31536000; includeSubDomains

# Hashed asset names, safe to cache forever.
/_astro/*
  Cache-Control: public, max-age=31536000, immutable
`;

writeFileSync(join(DIST, '_headers'), headers);
console.log(`_headers written, pinning ${scriptHashes.size} inline script(s)`);
